options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'Build docker image'
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/ultra-glyph-442600-d1/my-docker-repo/bansach:$COMMIT_SHA', '.']

- name: 'Push docker image to repository'
  args: ['push', 'asia-southeast1-docker.pkg.dev/ultra-glyph-442600-d1/my-docker-repo/bansach:$COMMIT_SHA']
images: ['asia-southeast1-docker.pkg.dev/ultra-glyph-442600-d1/my-docker-repo/bansach:$$COMMIT_SHA']


