apiVersion: apps/v1
kind: Deployment
metadata:
  name: bansach
spec:
  selector:
    matchLabels:
      app: bansach
  replicas: 1
  template:
    metadata:
      labels:
        app: bansach
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/ultra-glyph-442600-d1/my-docker-repo/bansach
          name: bansach
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bansach-service
spec:
  selector:
    app: bansach
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
